### ISSUE TITLE
bug: floating headers become transparent

### ISSUE THREAD

**Issue by aleesteele** [Threespot/freeze-scroll#1]
when scrolling is disabled, floating headers become transparent (possibly other floating elements as well?)

**Comment by tedw** [comment]
Hi @aleesteele, thanks for using our little JS library! 😊 

Are you referring to floating elements that use `position: sticky;` or do you mean elements that have `float` applied?

If there’s a link you could share showing this effect that would be ideal. If not, a [CodePen](http://codepen.com) or [JSbin](https://jsbin.com) demo would be really helpful.

Thanks!

**Comment by tedw** [comment]
@aleesteele Just saw the email you sent with more info, thanks! Will clone the [health-commission](https://github.com/CSIS-iLab/health-commission) site and see if I can figure out what’s going on.

**Comment by aleesteele** [comment]
Hi @tedw, thanks so much for your help!
I forked the code base of the project I'm working on, linked [here](https://github.com/aleesteele/health-commission). Feel free to clone the repo and use it on your local machine, as it was the easiest way to demonstrate this change without creating an entirely new website.

These are the main affected files:
- `members.js` dynamically affects the site header: https://github.com/aleesteele/health-commission/blob/master/assets/_js/members.js
- the `header.scss` sass file determines the opacity, position, etc of the header: https://github.com/aleesteele/health-commission/blob/master/assets/_sass/layout/_header.scss

We use `position: fixed` to stick to the top of the page, not either `float` or `stick`. Would that help?

**Comment by aleesteele** [comment]
For context: we toggle the class `menu-open` when the menu is open on the mobile version of the site:
- https://github.com/aleesteele/health-commission/blob/master/assets/_js/main-menu.js#L7-L21
- https://github.com/aleesteele/health-commission/blob/master/assets/_js/site-header.js#L39-L42
- https://github.com/aleesteele/health-commission/blob/master/assets/_sass/base/_base.scss#L29-L32

**Comment by tedw** [comment]
Ok, I know what the issue is. When you call `scroll.freeze();` the following styles are applied:

```css
html.js-no-scroll {
  height: 100% !important;
}

.js-no-scroll body {
  height: 100%;
  overflow: hidden !important;
  position: fixed !important;
  width: 100% !important;
}
```

These styles set the height of the html and body tags to 100% and prevent overflow, which has the effect of setting `window.scrollY` back to `0`. It then uses inline styles on the body to shift the visible part of the pack back to where it was (e.g. `height: calc(100% + 2064px); top: -2064px;`), which is why users don’t perceive a scroll change.

This change in scroll position triggers the scroll event listener in `site-header.js`, and since `window.scrollY` equals `0`, it applies the `site-header--trigger-minimal` class.

I think the simplest solution would be to check for the `'js-no-scroll` class on the html element and ignore the event if it’s present.

```js
window.addEventListener('scroll', function() {
  // Ignore scroll events trigger by freeze-scroll when opening modal windows
  if (document.documentElement.classList.contains('js-no-scroll')) {
    return false
  }
  …
})
```

I tested locally and it seemed to work. Let me know if you run into any other issues!

**Comment by tedw** [comment]
FYI, just updated the readme to let people know about this quirk of how the script works.
https://github.com/Threespot/freeze-scroll#usage

**Comment by aleesteele** [comment]
Thanks so much, @tedw! This worked wonderfully!
